const api = {
  'baseUrl': 'http://localhost/houtai/',
  'verifycode': 'admin/codeimg',
  'userLogin' : 'admin/checkuser',
  'siteinfo' : 'admin/info',
  'imageupload': 'admin/image-upload',
  'siteInfoUpdate': 'admin/info-update',
  'addKeyword' : 'admin/keyword-add',
  'keywords' : 'admin/keyword',
  'keywordsNoPage': 'admin/keyword-no-page',
  'keywordsCount' : 'admin/keyword-count',
  'deleteKeywords' : 'admin/keyword-del',
  'updateKeyword' : 'admin/keyword-modify',
  'picCateList' : 'admin/pic-cate',
  'addPicCate' : 'admin/pic-cate-add',
  'updatePicCateOrder': 'admin/pic-cate-order',
  'deletePicCate' : 'admin/pic-cate-del',
  'updatePicCateRec' : 'admin/pic-cate-rec',
  'PicCateDetail' : 'admin/pic-cate-detail',
  'updatePicCate': 'admin/pic-cate-update',
  'picList': 'admin/pic-list',
  'picCheck': 'admin/pic-check',
  'updatePicOrder': 'admin/pic-order',
  'deletePic' : 'admin/pic-del',
  'keywordsForPicCate' : 'admin/pic-cate-keyword',
  'picAdd' : 'admin/pic-add-do',
  'picDetail' : 'admin/pic-detail',
  'keywordsForPic' : 'admin/pic-keywords',
  'picUpdate' : 'admin/pic-update',
};
export default api;
